# Generated by Django 5.1.3 on 2025-03-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points_balance',
            field=models.IntegerField(default=0),
        ),
    ]
